# Generated by Django 4.2.5 on 2023-09-22 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(blank=True, max_length=100, null=True, verbose_name='Авторы')),
                ('isbn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['authors'],
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория')),
                ('isbn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['categories'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название книги')),
                ('isbn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порядковый номер')),
                ('pageCount', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц книги')),
                ('thumbnailUrl', models.ImageField(blank=True, default='', null=True, upload_to='gallary/%y/%m/%d', verbose_name='Фото')),
                ('shortDescription', models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое описание книги')),
                ('longDescription', models.TextField(blank=True, null=True, verbose_name='Полное описание книги')),
                ('is_published', models.BooleanField(blank=True, default=True, null=True, verbose_name='Опубликовано')),
                ('authors', models.ManyToManyField(to='book_app.author')),
                ('categories', models.ManyToManyField(to='book_app.categories')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
