# Generated by Django 4.2.5 on 2023-10-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_alter_commentuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishedDate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время создания'),
        ),
    ]
